### ISSUE TITLE
Create base58 module (and remove dependency)

### ISSUE THREAD

**Issue by SimonLab** [dwyl/cid#23]
At the moment we are using the following package https://github.com/nocursor/b58 to convert the cid to base58.

This package provide much more than we need and to avoid having another dependency we can add a simplified version of base58 to the cid project

- [x] Create a hex.pm package `B58` which expose the function `B58.encode` which takes one parameter (a binary) and returns a string containing only the set of characters from the base58 btc:
`123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz`

ref: https://en.wikipedia.org/wiki/Base58

**Comment by nelsonic** [comment]
@SimonLab thanks for opening this issue. ✅ 
https://hex.pm/packages/b58
![image](https://user-images.githubusercontent.com/194400/51911276-543a0d00-23c9-11e9-8f7e-419aed8971ea.png)

Let's fix this **`404`** with the following repo: https://github.com/dwyl/elixir-base58-encode

**Comment by SimonLab** [comment]
Just for info if people are looking for https://github.com/nocursor/b58 on hex, the name of the package is  basefiftyheight: https://hex.pm/packages/basefiftyeight

**Comment by nelsonic** [comment]
@SimonLab I know ... the naming is a _fail_. ideally it should be base58encode
https://hex.pm/packages/base58encode which describes ***exactly*** what the package does (_or will do_)

**Comment by SimonLab** [comment]
The package is now public at https://hex.pm/packages/b58
I'm going to add it to the dependency of CID and check that all our tests are still working

**Comment by SimonLab** [comment]
error when trying to run `mix test` (`mix deps.get was run before)
![image](https://user-images.githubusercontent.com/6057298/52054204-a7d86200-2553-11e9-8e79-d78c04f1c83d.png)

**Comment by SimonLab** [comment]
The error is due to a mismatch in the base58encode package in the name, see https://github.com/dwyl/base58encode/issues/11

**Comment by SimonLab** [comment]
We are now using b58 elixir package in CID, see #30
