### ISSUE TITLE
Property Based Tests with IPFS

### ISSUE THREAD

**Issue by Danwhy** [dwyl/cid#24]
I think it would be a good idea to run some property based tests for this module, where we generate strings, maps and structs and run our `Cid.cid` function.

We can then compare the results of these function calls with the ipfs result of the same values.

This will provide us with a comprehensive list of tests, that change every time we run them, meaning we can be sure the module is creating the cid correctly every time.

- [x] install ipfs to travis
- [x] create property based tests
  - [x] generate random strings/maps
  - [x] compare result of cid function to ipfs function

**Comment by Danwhy** [comment]
This will require us to download ipfs to travis to run our tests:

https://docs.ipfs.io/introduction/install/

**Comment by nelsonic** [comment]
@Danwhy _now_ you're onto something! 😍

**Comment by RobStallion** [comment]
Going to try and install IPFS locally on @Danwhy 's machine with curl and the commands from IPFS. If we can do this on his machine then we should be able to recreate these steps with travis.

**Comment by nelsonic** [comment]
@Danwhy / @RobStallion _thank you_ for adding the **`T4`** Label (_which seems reasonable if you document how to set-up IPFS CLI on Travis-CI and add some notes on Property-based-Testing to the `README.md` (_or a separate doc_) of https://github.com/dwyl/learn-elixir  as per https://github.com/dwyl/learn-elixir/issues/93

_Please_ take a few minutes to follow https://github.com/dwyl/product-ux-research/issues/34 
(_i.e. install and use the app to track the **actual** time you take on this issue..._)

Thanks! (_and keep up the great effort!_) ✨

**Comment by RobStallion** [comment]
Travis failed to build with the updated yml file. 

```bash
$ ./install.sh
We cannot install ./ipfs in one of the directories /usr/local/bin /usr/bin
It seems that we do not have the necessary write permissions.
Perhaps try running this script as a privileged user:
    sudo ./install.sh
The command "./install.sh" failed and exited with 1 during .
Your build has been stopped.
```

Going to try suggested fix.

**Comment by Danwhy** [comment]
<img width="706" alt="screen shot 2019-01-29 at 14 51 23" src="https://user-images.githubusercontent.com/8939909/51916531-68840700-23d5-11e9-9d38-3cb03dfd21ca.png">

Installed correctly, just need to make sure we `cd` back out of the ipfs directory

**Comment by RobStallion** [comment]
Successfully installed IPFS on travis...
![image](https://user-images.githubusercontent.com/15571853/51917033-8140ec80-23d6-11e9-920e-ac93fd74144b.png)

**Comment by RobStallion** [comment]
forgetting basic steps...

![image](https://user-images.githubusercontent.com/15571853/51923784-8f493a00-23e3-11e9-9090-457f97ab0cec.png)

Going to add ipfs init to travis yml

**Comment by Danwhy** [comment]
Tests added and running on Travis :+1:
