### ISSUE TITLE
Cannot get codecov badge to work

### ISSUE THREAD

**Issue by RobStallion** [dwyl/cid#28]
Have been trying to add codecov badge but cannot seem to get it to work for some reason.
Relates to this pr https://github.com/dwyl/cid/pull/25#issuecomment-458969612

**Comment by RobStallion** [comment]
Screenshot taken from travis

![image](https://user-images.githubusercontent.com/15571853/51994385-8c644d00-24a8-11e9-9047-edab00409875.png)

```

==> Travis CI detected.
    project root: .
    Fixing merge commit SHA
--> token set from env
    Yaml not found, that's ok! Learn more at http://docs.codecov.io/docs/codecov-yaml
==> Running gcov in . (disable via -X gcov)
==> Python coveragepy not found
==> Searching for coverage reports in:
    + .
--> No coverage report found.
    Please visit http://docs.codecov.io/docs/supported-languages
```

**Comment by RobStallion** [comment]
Went to the following link mentioned in the above from travis... `http://docs.codecov.io/docs/supported-languages`

This link lists a bunch of supported languages, elixir being one of them. The [elixir link](https://github.com/codecov/example-elixir).

Looked at the elixir link example and saw that they had defined a `coveralls.json` command in there `mix.exs` file

```elixir
      preferred_cli_env: [
        "coveralls": :test,
        "coveralls.html": :test,
        "coveralls.json": :test,
      ],
```

I have added this to ours now...
```elixir
      preferred_cli_env: [
        coveralls: :test,
        "coveralls.detail": :test,
        "coveralls.post": :test,
        "coveralls.html": :test,
        "coveralls.json": :test,
        all_tests: :test
      ]
```

**Comment by nelsonic** [comment]
@robstallion did you manage to get it working?

> if not, please see: https://github.com/dwyl/phoenix-chat-example/blob/master/.travis.yml

**Comment by RobStallion** [comment]
@nelsonic Not yet no 😖 + 😕

**Comment by nelsonic** [comment]
Checkout how it’s done in the Chat example:
https://github.com/dwyl/phoenix-chat-example/

**Comment by RobStallion** [comment]
Looking at it now 👍

**Comment by RobStallion** [comment]
aliais from https://github.com/dwyl/phoenix-chat-example/
```elixir
  defp aliases do
    [
      "ecto.setup": ["ecto.create", "ecto.migrate", "run priv/repo/seeds.exs"],
      "ecto.reset": ["ecto.drop", "ecto.setup"],
      test: ["ecto.create --quiet", "ecto.migrate", "test"],
      cover: ["coveralls.json"],
      "cover.html": ["coveralls.html"]
    ]
  end
```
(cover is the important one here)

.travis.yml from https://github.com/dwyl/phoenix-chat-example/
```elixir
language: elixir
elixir: # Latest version of Elixir
  - 1.7
addons: # ensure that Travis-CI provisions a DB for our test:
  postgresql: '9.5'
env:
  - MIX_ENV=test
script: # run the tests:
  - mix cover
after_success:
  - bash <(curl -s https://codecov.io/bash)
```

Added this to cid
```elixir
script:
  - mix coveralls.json
```

But still having the same issue

**Comment by RobStallion** [comment]
I really can't see what I am missing 😖

**Comment by RobStallion** [comment]
Added 25minute label because I feel like that's all it should have taken but I am doing something wrong and it has taken much longer

**Comment by nelsonic** [comment]
@RobStallion try adding the "Repository Upload Token" as a Travis-CI Environment Variable.
(_LMK if you are still stuck, we can do a quick Google Hangout to get it resolved ..._)

**Comment by RobStallion** [comment]
@nelsonic I'm guessing that is this token you are talking about...
![image](https://user-images.githubusercontent.com/15571853/51998905-7ad37300-24b1-11e9-99ca-3bed055376cc.png)
(have changed the token now)

which I have tried adding (was just putting that into a comment when you responded) with no luck. 

A hangouts would be GREAT. Just let me know when you are free. 
(I have a really strong feeling I am going to be kicking myself forever over this)

**Comment by nelsonic** [comment]
@RobStallion standard "abv" hangouts link? (_I'm on it now..._)

**Comment by nelsonic** [comment]
# "_Once you eliminate the impossible, whatever remains, no matter how improbable, must be the truth._" ~ Sherlock Holmes / Arthur Conan Doyle 

What I always think when I'm debugging something ... 💻 
Reduce the variables/unknowns until you have just the root cause of the problem. 🐞

**Comment by nelsonic** [comment]
@RobStallion thanks for the hangout call to debug this. 💻 <> 💻 
I learned not to override the `mix test` command. 👍 
Looking forward to reading your writeup on this. 📝 
Please consider adding a `codecov.md` file to https://github.com/dwyl/learn-elixir 💧 
and linking to it from the main `README.md` 🔗 
 it doesn't have to take more than 1 x 🍅 
and will be a _huge_ help to anyone _else_ trying to replicate this in the _near_ future. 🆘 
Thanks again! ✨

**Comment by RobStallion** [comment]
@nelsonic 

> @RobStallion thanks for the hangout call to debug this. 💻 <> 💻

Thank you for the hangout call

Will do for the rest 👍

**Comment by nelsonic** [comment]
# `T25m` ... 3 hours later ... 🙄

![homer-gif-simple](https://frinkiac.com/gif/S12E06/1081664/1085418.gif?b64lines=T2YgY291cnNlLgogSXQncyBzbyBzaW1wbGUuIFdhaXQuIE5vLAogaXQncyBub3QuCkl0J3MgbmVlZGxlc3NseSBjb21wbGljYXRlZC4=)

# 😜

**Comment by RobStallion** [comment]
![image](https://user-images.githubusercontent.com/15571853/52007512-7feeed00-24c6-11e9-95bc-ce040aa749b6.png)

![image](https://user-images.githubusercontent.com/15571853/52007583-a6ad2380-24c6-11e9-8b67-c6d4440851fb.png)

![image](https://user-images.githubusercontent.com/15571853/52008201-0e17a300-24c8-11e9-9c26-b636e72c141f.png)

![image](https://user-images.githubusercontent.com/15571853/52008358-6058c400-24c8-11e9-865b-71cc9de055c4.png)
TEARS OF JOY

**Comment by Cleop** [comment]
@RobStallion - so what was the issue? It looks from your commit like the test aliases were breaking it? Can you explain this in any more detail?
