### ISSUE TITLE
Publish first version

### ISSUE THREAD

**Issue by SimonLab** [dwyl/cid#31]
I think this application will soon arrive at a stage where it is publishable. For that we need
- Define the name of the package. cid is already taken: https://hex.pm/packages/cid , should we go with `ex_cid`? see https://github.com/dwyl/cid/issues/22#issuecomment-458253874

- Make sure that all the mix.exs required value are defined, see https://github.com/dwyl/learn-elixir#publishing

**Comment by RobStallion** [comment]
I like ex_cid more personally

**Comment by nelsonic** [comment]
@simonlab / @robstallion any reason we don't use the shorter (_no underscore_) version? https://hex.pm/packages/excid
![image](https://user-images.githubusercontent.com/194400/52068538-c3a03000-2574-11e9-8108-93dd8a57a276.png)

**Comment by SimonLab** [comment]
No other reason for me, I think I saw a couple of package using this convention (e.g ex_doc, ex_multihash) but it doesn't mean we can't use `excid`.
Happy to change the name, @RobStallion ?

**Comment by RobStallion** [comment]
@SimonLab @nelsonic I don't mind either really. I was thinking along the same lines as you @SimonLab but there are other modules that don't have the underscore as well, excoveralls being one.

**Comment by RobStallion** [comment]
@SimonLab @nelsonic I have to pop out now and won't be back till about 7:30/8pm.

I will follow the [instructions](https://github.com/dwyl/learn-elixir#publishing) and update the readme with my thoughts/comments then if that is okay with you guys?

**Comment by RobStallion** [comment]
```sh
Generated excid app
Docs successfully generated.
View them at "doc/index.html".
No authenticated user found. Do you want to authenticate now? [Yn]
```

After running `mix hex.publish` I got the above command. All it meant was that I had to log into hex. Wasn't a big deal but the step wasn't in the readme so I'll add it. 

Was really straightforward though. 

Package can be found https://hex.pm/packages/excid

**Comment by SimonLab** [comment]
Well spotted @RobStallion , I didn't have this login issue as I've registered just before on hexpm.
Don't forget to create a tag/release on Github for this version.

**Comment by RobStallion** [comment]
Ahh thanks for reminding me. That is in the readme sorry. Just slipped my mind. On it now 👍

**Comment by RobStallion** [comment]
Done. Thanks @SimonLab

**Comment by SimonLab** [comment]
published at https://hex.pm/packages/excid
