### ISSUE TITLE
Module doc does not display the same way in hex as in text editor

### ISSUE THREAD

**Issue by RobStallion** [dwyl/cid#35]
![image](https://user-images.githubusercontent.com/15571853/52138605-8d7eb100-2645-11e9-8c77-e54fe311dfe9.png)

```
  Currently only produces a default v1 CID.
  Currently only uses the "raw" codec
  Data provided must be under 256Kb in order for the CID to match the one
  returned by IPFS

  For more info on CIDs and IPFS see the following...
  https://ipfs.io/
  https://pascalprecht.github.io/posts/content-identifiers-in-ipfs/
  https://github.com/dwyl/learn-ipfs/issues
```

Update text so that it is clear when on hex pm

**Comment by nelsonic** [comment]
Indentation fixed in `@doc` examples so they now appear correctly on: https://hexdocs.pm/excid/Cid.html#functions

![image](https://github.com/dwyl/cid/assets/194400/223bf013-166e-4343-821f-c0e4cea5fa9b)
