### ISSUE TITLE
Please Add @dwyl as Co-owner of excid Hex.pm Package

### ISSUE THREAD

**Issue by nelsonic** [dwyl/cid#38]
Hi @RobStallion hope you are well! 👋 
When you are next back at your desk, could you please add [@dwyl](https://hex.pm/users/dwyl) as a co-owner of the `excid` package on Hex.pm  https://hex.pm/packages/excid 

![image](https://user-images.githubusercontent.com/194400/80799743-91c6b080-8b9f-11ea-9c84-bdd43a74da07.png)

It's a single command in your terminal: 💻 

```
mix hex.owner add excid dwyl
```

That way we can publish a new version when needed. 📦 
Thanks! ☀️

**Comment by RobStallion** [comment]
@nelsonic Will do that ASAP. Long overdue sorry 😬

**Comment by RobStallion** [comment]
Hey @nelsonic This should be done now. Please let me know if it is working as you expect and let me know if you need anything else 👍

**Comment by nelsonic** [comment]
@RobStallion thanks! ❤️

**Comment by nelsonic** [comment]
![dwyl-coowner-of-excid](https://user-images.githubusercontent.com/194400/87398001-28a2e680-c5ad-11ea-9363-a5ab06db1afa.png)

Thanks again Rob! 🚀
