### ISSUE TITLE
Please Test `Elixir` `cid` matches the output of `Go` and `Dart` version 🧪 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/cid#47]
We have an issue with the build failing for our `imgup` app because the `cid` (which is used as the filename) for the images uploaded to `S3` has changed ... 😕 
We need to: 
+ [ ] investigate & confirm that the `cid` created in `Elixir` is _identical_ to the one created by `Go` 
+ [x] and correspondingly, _identical_ to the one created by the `Dart` implementation of `cid`. 

This is as easy as:

```sh
cd ~/code/cid
iex -S mix

iex(1)> Cid.cid("hello")
"bafkreibm6jg3ux5qumhcn2b3flc3tyu6dmlb4xa7u5bf44yegnrjhc4yeq"
```

**Comment by LuchoTurtle** [comment]
It's probably this line change:

https://github.com/dwyl/cid/commit/7c3e41bc9750ffbc31ae6b64f3f50ccfa6af928c

`imgup` is failing because the CID that is being created is becoming `base58BTC` instead of the previous `base32`

**Comment by nelsonic** [comment]
Indeed. `base58` is preferable to `base32` because it uses fewer characters to represent the same `cid`. 💭

**Comment by nelsonic** [comment]
Lowering the priority of this in light of the fact that https://github.com/dwyl/imgup/pull/122 is merged and ![GitHub Workflow Status](https://img.shields.io/github/actions/workflow/status/dwyl/imgup/ci.yml?label=build&style=flat-square&branch=main) on `main` of `imgup` ✅ 

We still want to _confirm_ that `cid` created in `Dart` matches the one in `Elixir`. 
That is probably a `T5m` task if you have the project open on your `Mac` ...

**Comment by LuchoTurtle** [comment]
Running a locally created test on `dart_cid` yields a correct response:

```dart
      String input = 'hello';
      final output = CID.createCid(input, Multibase.base32).cid;

      expect(output == "bafkreibm6jg3ux5qumhcn2b3flc3tyu6dmlb4xa7u5bf44yegnrjhc4yeq", true);
```

```sh
00:01 +28: All tests passed!  
```

**Comment by nelsonic** [comment]
Cool. As long as they match we're all good. 👌 🙇

**Comment by LuchoTurtle** [comment]
@nelsonic can't find the repo for the `Go` project. Where is it?

**Comment by nelsonic** [comment]
https://github.com/dwyl/cid/blob/b675c95d8b41cfb4331f19d0a9c239acfcd63739/.github/workflows/ci.yml#L14-L21
