### ISSUE TITLE
Add Youtube as Example in Real World Examples

### ISSUE THREAD

**Issue by nelsonic** [dwyl/cid#9]
+ [x] Add example of YouTube IDs e.g: https://www.youtube.com/watch?v=4Mtw3vBQYOg
+ [x] Make it similar to the Instagram one. see: https://github.com/dwyl/cid#instagrams-apparently-random-string-ids

**Comment by RobStallion** [comment]
The first ever youtube video

https://www.youtube.com/watch?v=jNQXAC9IVRw

Newer youtube video
https://www.youtube.com/watch?v=g5eGKw4TWbU

another 2018 video
https://www.youtube.com/watch?v=fYyDQBG_tYc

All videos seem to have similar urls. This leads me to believe that youtube never had an incrementing system for URLs like the example of instagram in the readme. 

Appears that they do something more similar to [this](https://github.com/dwyl/cid#google-url-shortener) example in the readme (which makes sense as google also own youtube).

**Comment by RobStallion** [comment]
@nelsonic given that the urls for youtube videos appear to be working in very similar way to the [google shortener](https://github.com/dwyl/cid#google-url-shortener) example, do you still want to add a Youtube example?

**Comment by nelsonic** [comment]
@RobStallion YT has an 11 character base58 string as ID. 
The fact that they have _always_ used an 11 char string is indicative that the YT founders were _planning_ for "scale" from Day One. 💡 
The reason I opened this issue was not because I thought that YT was "different" from Google URL shortener. On the contrary, the _reason_ I want the YT example is that it's _highly relevant_ to the 1.8Bn people who use YT every day, most of whom have _shared_ a YT video URL and will be _familiar_ with the IDs.
I'm happy to add the example.

**Comment by RobStallion** [comment]
@nelsonic I'm happy to at it. That wasn't this issue at all sorry. 

I didn't think about it from that point of view at all. That is a really good point and I'm happy to up write that up 👍

**Comment by RobStallion** [comment]
[base58](https://en.wikipedia.org/wiki/Base58https://en.wikipedia.org/wiki/Base58) uses all the upper and lower case letters in the alphabet (with the exception of O and I, capital versions of the letters o and i, and the lowercase version of the letter L) and the number 1-9.

Youtube does not appear to be using base 58
jNQXAC9IVRw <-- contains a capital i
fYyDQBG_tYc <- contains an underscore 

However it is not using base64 either. It appears to be using the same character set as the google url shortener from the example 
```
0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz
```

Can't be certain but it would make sense as youtube is owned by google

**Comment by RobStallion** [comment]
@nelsonic Can this issue be closed now?

**Comment by nelsonic** [comment]
@RobStallion thanks again. 👍
